### ISSUE TITLE
execute tscaftererror   What's the situation 

### ISSUE THREAD

**Issue by 44-83** [ParveenBhadooOfficial/Telegram-BhadooCloud#2]
src/index.ts:602:32 - error TS2339: Property 'INDEX_DOMAIN' does not exist on type '{ readonly TOKEN: string; readonly ARIA_SECRET: string; readonly ARIA_DOWNLOAD_LOCATION: string; readonly ARIA_DOWNLOAD_LOCATION_ROOT: string; readonly ARIA_FILTERED_DOMAINS: any[]; ... 8 more ...; readonly COMMANDS_USE_BOT_NAME: { ...; }; }'.

602         var rawurl = constants.INDEX_DOMAIN + fileName + "/";
                                   ~~~~~~~~~~~~

src/index.ts:604:32 - error TS2339: Property 'INDEX_DOMAIN' does not exist on type '{ readonly TOKEN: string; readonly ARIA_SECRET: string; readonly ARIA_DOWNLOAD_LOCATION: string; readonly ARIA_DOWNLOAD_LOCATION_ROOT: string; readonly ARIA_FILTERED_DOMAINS: any[]; ... 8 more ...; readonly COMMANDS_USE_BOT_NAME: { ...; }; }'.

604         var rawurl = constants.INDEX_DOMAIN + fileName ;
                                   ~~~~~~~~~~~~

Found 2 errors.

**Comment by ParveenBhadooOfficial** [comment]
fixed it. 
edit https://github.com/ParveenBhadooOfficial/Telegram-BhadooCloud/blob/master/src/.constants.js
Line 5 with your own index.
