### ISSUE TITLE
Execution error

### ISSUE THREAD

**Issue by 44-83** [ParveenBhadooOfficial/Telegram-BhadooCloud#3]
First executed to get  credentials.json （ client_secret.json No problem）
Tips
 A2C: Websocket opened. Bot ready.
Failed to start the download. Unauthorized

**Comment by 44-83** [comment]
I use https://github.com/out386/aria-telegram-mirror-bot to get credentials.json  
Execution Success
Want to ask  How to let bot Send GD link and INDEX_DOMAIN link at the same time

**Comment by ParveenBhadooOfficial** [comment]
I'm unable to understand what you're asking precisely.

**Comment by Ex-Communicad0** [comment]
@ParveenBhadooOfficial  Check Your TG PM i have send you what problems i get... same issue .... in bot reply terminal not showing auth url to verify.... Please Check your PM (name:Jhon Wick)

**Comment by ParveenBhadooOfficial** [comment]
Video Added.

**Comment by Ex-Communicad0** [comment]
Video Removed By User???😢
